[build]
  publish = "build/web"
  command = """
    if [ ! -d "$HOME/flutter" ]; then git clone https://github.com/flutter/flutter.git -b stable --depth 1 "$HOME/flutter"; fi
    export PATH="$HOME/flutter/bin:$PATH"
    flutter config --enable-web
    flutter pub get
    flutter build web --release --no-wasm-dry-run --pwa-strategy=none --dart-define=API_BASE_URL=$API_BASE_URL --dart-define=ORS_API_KEY=$ORS_API_KEY
  """

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
